### ISSUE TITLE
gRPC call is failing with "ValueError: metadata was invalid"

### ISSUE THREAD

**Issue by ymotongpoo** [ymotongpoo/shakesapp-python#2]
https://github.com/ymotongpoo/shakesapp-python/commit/1141004fb8e616afe4ff447afa311c74c0a0cf1e failed with the message "ValueError: metadata was invalid" when I tried gRPC instrumentation.

It seem the value of `X-Cloud-Trace-Context` contained some invalid key for gRPC communication.

Full message logs:

```
[client] [2021-03-12 07:12:55,481] ERROR in app: Exception on / [GET]
[client] Traceback (most recent call last):
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
[client]     response = self.full_dispatch_request()
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
[client]     rv = self.handle_user_exception(e)
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
[client]     reraise(exc_type, exc_value, tb)
[client]   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[client]     raise value
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
[client]     rv = self.dispatch_request()
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
[client]     return self.view_functions[rule.endpoint](**req.view_args)
[client]   File "/usr/local/lib/python3.8/site-packages/client.py", line 105, in main_handler
[client]     resp = stub.GetMatchCount(shakesapp_pb2.ShakespeareRequest(query=q))
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 56, in __call__
[client]     return self._interceptor.intercept_unary(
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/_client.py", line 177, in intercept_unary
[client]     result = invoker(request, metadata)
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 53, in invoker
[client]     return self._base_callable(request, timeout, metadata, credentials)
[client]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 921, in __call__
[client]     state, call, = self._blocking(request, timeout, metadata, credentials,
[client]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 903, in _blocking
[client]     call = self._channel.segregated_call(
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc._segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 360, in grpc._cython.cygrpc._segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 253, in grpc._cython.cygrpc._call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 61, in grpc._cython.cygrpc._raise_call_error
[client] ValueError: metadata was invalid: ('X-Cloud-Trace-Context', 'ec324242777a96a565c3f7f6103bd85f/3045927119593523823;o=1')
[loadgen] {"event": "HTTP request error: HTTP Error 500: INTERNAL SERVER ERROR", "severity": "warning", "timestamp": "2021-03-12T07:12:55.985396Z"}
[loadgen] {"event": "end request to client", "severity": "info", "timestamp": "2021-03-12T07:12:55.985635Z"}
[loadgen] {"event": "start request to client", "severity": "info", "timestamp": "2021-03-12T07:12:58.641455Z"}
[loadgen] {"event": "call_client start", "severity": "info", "timestamp": "2021-03-12T07:12:58.641545Z"}
[client] {"event": "request to server with query: world", "severity": "info", "timestamp": "2021-03-12T07:12:58.644973Z"}
[client] E0312 07:12:58.645546602      14 call.cc:919]                validate_metadata: {"created":"@1615533178.645526715","description":"Illegal header key","file":"src/core/lib/surface/validate_metadata.cc","file_line":44,"offset":0,"raw_bytes":"58 2d 43 6c 6f 75 64 2d 54 72 61 63 65 2d 43 6f 6e 74 65 78 74 'X-Cloud-Trace-Context'\u0000"}
[client] [2021-03-12 07:12:59,563] ERROR in app: Exception on / [GET]
[client] Traceback (most recent call last):
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
[client]     response = self.full_dispatch_request()
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
[client]     rv = self.handle_user_exception(e)
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
[client]     reraise(exc_type, exc_value, tb)
[client]   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[client]     raise value
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
[client]     rv = self.dispatch_request()
[client]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
[client]     return self.view_functions[rule.endpoint](**req.view_args)
[client]   File "/usr/local/lib/python3.8/site-packages/client.py", line 105, in main_handler
[client]     resp = stub.GetMatchCount(shakesapp_pb2.ShakespeareRequest(query=q))
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 56, in __call__
[client]     return self._interceptor.intercept_unary(
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/_client.py", line 177, in intercept_unary
[client]     result = invoker(request, metadata)
[client]   File "/usr/local/lib/python3.8/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 53, in invoker
[client]     return self._base_callable(request, timeout, metadata, credentials)
[client]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 921, in __call__
[client]     state, call, = self._blocking(request, timeout, metadata, credentials,
[client]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 903, in _blocking
[client]     call = self._channel.segregated_call(
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc._segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 360, in grpc._cython.cygrpc._segregated_call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 253, in grpc._cython.cygrpc._call
[client]   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 61, in grpc._cython.cygrpc._raise_call_error
[client] ValueError: metadata was invalid: ('X-Cloud-Trace-Context', 'a13ae8553d2738f0b85e980bb52219d2/774288543953011985;o=1')
```

**Comment by aabmass** [comment]
@ymotongpoo we've got an issue here for this https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/109

Short term, I am going to update the propagator to use lowercase `x-cloud-trace-context`. IMO, OpenTelemetry instrumentation or the gRPC instrumentation should be lowercasing the keys for us, but we can do both :)
